// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'outerSearchBar': string;
  'outerSearchDiscard': string;
  'outerSearchOptions': string;
  'searchBar': string;
  'searchContainer': string;
  'searchOptions': string;
}
export const cssExports: CssExports;
export default cssExports;
