// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'groupHeaderContent': string;
  'groupHeaderRow': string;
  'rotate': string;
  'spin': string;
}
export const cssExports: CssExports;
export default cssExports;
